version: 2
env:
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
builds:
  - id: shieldx-binaries
    main: ./cmd/policyctl
    binary: policyctl
    goos: [linux]
    goarch: [amd64]
    flags: ["-trimpath"]
    ldflags:
      - -s -w -buildid=
archives:
  - id: default-archive
    builds: [shieldx-binaries]
    format: tar.gz
checksum:
  name_template: checksums.txt
snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}
changelog:
  skip: true