apiVersion: v1
kind: ConfigMap
metadata:
  name: cosign-config
  namespace: shieldx-system
data:
  policy.yaml: |
    apiVersion: v1alpha1
    kind: ClusterImagePolicy
    metadata:
      name: shieldx-image-policy
    spec:
      images:
      - glob: "registry.shieldx.io/shieldx/*"
      authorities:
      - keyless:
          url: https://fulcio.sigstore.dev
          identities:
          - issuer: https://github.com/login/oauth
            subject: "https://github.com/shieldx-security/*"
      - key:
          data: |
            -----BEGIN PUBLIC KEY-----
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7+R9dC4VgaD0sqs6i7qCrS2WS/14
            cBTBFJbVms9uKOWHSQAIrdgExP5S2N+M/mLSRBz4a5UuV1J2+QHshQTUBw==
            -----END PUBLIC KEY-----
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cosign-policy-controller
  namespace: shieldx-system
spec:
  selector:
    matchLabels:
      app: cosign-policy-controller
  template:
    metadata:
      labels:
        app: cosign-policy-controller
    spec:
      serviceAccountName: cosign-policy-controller
      containers:
      - name: policy-controller
        image: gcr.io/projectsigstore/policy-controller:v0.8.0
        args:
        - --config-dir=/etc/cosign-policy
        - --webhook-name=policy.sigstore.dev
        - --port=8443
        - --cert-dir=/tmp/k8s-webhook-server/serving-certs
        volumeMounts:
        - name: cosign-policy
          mountPath: /etc/cosign-policy
          readOnly: true
        - name: webhook-certs
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          capabilities:
            drop:
            - ALL
      volumes:
      - name: cosign-policy
        configMap:
          name: cosign-config
      - name: webhook-certs
        secret:
          secretName: webhook-certs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cosign-policy-controller
  namespace: shieldx-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cosign-policy-controller
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingadmissionwebhooks", "mutatingadmissionwebhooks"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cosign-policy-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cosign-policy-controller
subjects:
- kind: ServiceAccount
  name: cosign-policy-controller
  namespace: shieldx-system