# Production Monitoring Configuration
# PERSON 3 - Business Logic & Infrastructure
# Prometheus, Grafana, AlertManager Setup

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'shieldx-prod'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Load rules
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # Credits Service
  - job_name: 'credits-service'
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
        - shieldx-prod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app]
      action: keep
      regex: credits-service
    - source_labels: [__meta_kubernetes_pod_name]
      target_label: instance
    - source_labels: [__meta_kubernetes_pod_ip]
      target_label: pod_ip
    metrics_path: /metrics
    scrape_interval: 10s

  # Shadow Evaluation Service
  - job_name: 'shadow-eval'
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
        - shieldx-prod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app]
      action: keep
      regex: shadow-eval
    - source_labels: [__meta_kubernetes_pod_name]
      target_label: instance
    metrics_path: /metrics
    scrape_interval: 10s

  # Locator Service
  - job_name: 'locator-service'
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
        - shieldx-prod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app]
      action: keep
      regex: locator
    metrics_path: /metrics
    scrape_interval: 10s

  # PostgreSQL Databases
  - job_name: 'postgresql'
    static_configs:
    - targets:
      - postgres-credits-exporter:9187
      - postgres-shadow-exporter:9187
      - postgres-cdefnet-exporter:9187
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
    - targets:
      - redis-exporter:9121
    scrape_interval: 30s

  # Node Exporter (Infrastructure)
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
    - role: node
    relabel_configs:
    - source_labels: [__address__]
      regex: '(.*):10250'
      replacement: '${1}:9100'
      target_label: __address__
    - source_labels: [__meta_kubernetes_node_name]
      target_label: node

  # Kubernetes API Server
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
    - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: default;kubernetes;https

---
# Alert Rules for Credits Service
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules-credits
  namespace: monitoring
data:
  credits_alerts.yml: |
    groups:
    - name: credits_service
      interval: 30s
      rules:
      # P0: Service Down
      - alert: CreditsServiceDown
        expr: up{job="credits-service"} == 0
        for: 1m
        labels:
          severity: critical
          service: credits
          team: person3
        annotations:
          summary: "Credits service is down"
          description: "Credits service {{ $labels.instance }} has been down for more than 1 minute"
          runbook_url: "https://docs.shieldx.io/runbooks/credits-down"

      # P0: High Error Rate
      - alert: CreditsHighErrorRate
        expr: |
          (
            rate(credits_operations_total{result="error"}[5m]) 
            / 
            rate(credits_operations_total[5m])
          ) > 0.05
        for: 5m
        labels:
          severity: critical
          service: credits
          team: person3
        annotations:
          summary: "Credits service high error rate"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}"

      # P0: Database Connection Pool Exhausted
      - alert: CreditsDatabasePoolExhausted
        expr: |
          (
            pg_stat_activity_count{datname="credits",state="active"} 
            / 
            pg_settings_max_connections{datname="credits"}
          ) > 0.9
        for: 2m
        labels:
          severity: warning
          service: credits
          team: person3
        annotations:
          summary: "Credits database connection pool near limit"
          description: "Connection pool usage is {{ $value | humanizePercentage }} for credits database"

      # P1: Slow Transactions
      - alert: CreditsSlowTransactions
        expr: |
          histogram_quantile(0.95, 
            rate(http_request_duration_seconds_bucket{job="credits-service"}[5m])
          ) > 1.0
        for: 10m
        labels:
          severity: warning
          service: credits
          team: person3
        annotations:
          summary: "Credits transactions are slow"
          description: "95th percentile transaction time is {{ $value }}s for {{ $labels.instance }}"

      # P0: Negative Balance Detected (Critical Bug)
      - alert: CreditsNegativeBalanceDetected
        expr: credits_negative_balance_count > 0
        for: 0m
        labels:
          severity: critical
          service: credits
          team: person3
          priority: P0
        annotations:
          summary: "CRITICAL: Negative balance detected"
          description: "Negative balance violation detected - immediate investigation required"
          runbook_url: "https://docs.shieldx.io/runbooks/negative-balance"

      # P1: Low Credit Alerts
      - alert: CreditsLowBalanceAlerts
        expr: credits_low_balance_alerts_active > 10
        for: 5m
        labels:
          severity: info
          service: credits
          team: person3
        annotations:
          summary: "Multiple tenants have low credit balance"
          description: "{{ $value }} tenants have triggered low balance alerts"

      # P1: High Transaction Volume
      - alert: CreditsHighTransactionVolume
        expr: rate(credits_operations_total[1m]) > 1000
        for: 5m
        labels:
          severity: info
          service: credits
          team: person3
        annotations:
          summary: "Credits service experiencing high transaction volume"
          description: "Transaction rate is {{ $value }} per second"

      # P0: Idempotency Key Collision
      - alert: CreditsIdempotencyCollision
        expr: credits_idempotency_collisions_total > 0
        for: 0m
        labels:
          severity: warning
          service: credits
          team: person3
        annotations:
          summary: "Idempotency key collision detected"
          description: "{{ $value }} duplicate transaction attempts detected"

      # P1: Audit Log Chain Break
      - alert: CreditsAuditLogChainBroken
        expr: credits_audit_chain_integrity_errors > 0
        for: 0m
        labels:
          severity: critical
          service: credits
          team: person3
          priority: P0
        annotations:
          summary: "CRITICAL: Audit log chain integrity violation"
          description: "Audit log chain has been broken - potential security incident"
          runbook_url: "https://docs.shieldx.io/runbooks/audit-chain-break"

---
# Alert Rules for Shadow Evaluation
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules-shadow
  namespace: monitoring
data:
  shadow_alerts.yml: |
    groups:
    - name: shadow_evaluation
      interval: 30s
      rules:
      # P0: Shadow Service Down
      - alert: ShadowServiceDown
        expr: up{job="shadow-eval"} == 0
        for: 2m
        labels:
          severity: warning
          service: shadow
          team: person3
        annotations:
          summary: "Shadow evaluation service is down"
          description: "Shadow service {{ $labels.instance }} is unavailable"

      # P1: Bayesian Test Inconclusive
      - alert: ShadowTestInconclusive
        expr: shadow_test_duration_hours > 168
        for: 1h
        labels:
          severity: info
          service: shadow
          team: person3
        annotations:
          summary: "A/B test running for over 1 week"
          description: "Test {{ $labels.test_id }} has been running for {{ $value }} hours without conclusive results"

      # P0: Shadow Deployment Without Testing
      - alert: ShadowUnsafeDeployment
        expr: shadow_deployments_without_testing > 0
        for: 0m
        labels:
          severity: critical
          service: shadow
          team: person3
          priority: P0
        annotations:
          summary: "CRITICAL: Deployment attempted without shadow testing"
          description: "A rule was deployed without proper A/B testing validation"
          runbook_url: "https://docs.shieldx.io/runbooks/unsafe-deployment"

      # P1: Low Sample Size
      - alert: ShadowLowSampleSize
        expr: shadow_test_sample_count < 100
        for: 24h
        labels:
          severity: info
          service: shadow
          team: person3
        annotations:
          summary: "A/B test has insufficient samples"
          description: "Test {{ $labels.test_id }} only has {{ $value }} samples after 24 hours"

---
# Grafana Dashboard ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-person3
  namespace: monitoring
data:
  person3-dashboard.json: |
    {
      "dashboard": {
        "title": "PERSON 3: Business Logic & Infrastructure",
        "tags": ["person3", "credits", "shadow", "database"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Credits Service Health",
            "type": "stat",
            "targets": [{
              "expr": "up{job=\"credits-service\"}"
            }],
            "gridPos": {"h": 4, "w": 6, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Credits Transaction Rate",
            "type": "graph",
            "targets": [{
              "expr": "rate(credits_operations_total[5m])"
            }],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 4}
          },
          {
            "id": 3,
            "title": "Database Connection Pool",
            "type": "graph",
            "targets": [
              {
                "expr": "pg_stat_activity_count{datname=\"credits\"}",
                "legendFormat": "Active Connections"
              },
              {
                "expr": "pg_settings_max_connections{datname=\"credits\"}",
                "legendFormat": "Max Connections"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 4}
          },
          {
            "id": 4,
            "title": "Shadow A/B Tests Progress",
            "type": "table",
            "targets": [{
              "expr": "shadow_test_probability_best"
            }],
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 12}
          },
          {
            "id": 5,
            "title": "P0 Violations",
            "type": "stat",
            "targets": [
              {
                "expr": "credits_negative_balance_count",
                "legendFormat": "Negative Balance"
              },
              {
                "expr": "credits_audit_chain_integrity_errors",
                "legendFormat": "Audit Chain Breaks"
              },
              {
                "expr": "shadow_deployments_without_testing",
                "legendFormat": "Unsafe Deployments"
              }
            ],
            "gridPos": {"h": 4, "w": 24, "x": 0, "y": 20}
          }
        ]
      }
    }
