name: Bug Report
description: Report a reproducible problem
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug.
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Short description
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide exact steps
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior / Logs
  - type: input
    id: version
    attributes:
      label: Version / Commit
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options: [low, medium, high, critical]
  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: OS, Go version, Docker version, etc.
