version: '3.8'

services:
  neo4j:
    image: neo4j:5.15
    environment:
      NEO4J_AUTH: neo4j/threatgraph2024
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./migrations:/var/lib/neo4j/import

  threatgraph:
    build: .
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: threatgraph2024
      PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - neo4j

volumes:
  neo4j_data:
  neo4j_logs: