openapi: 3.0.3
info:
  title: ShieldX Platform API
  version: 0.1.0
  description: Seed OpenAPI for key services (auth, ingress, ml-orchestrator)
servers:
  - url: http://localhost:8080
    description: auth-service
  - url: http://localhost:8081
    description: ingress
  - url: http://localhost:8090
    description: ml-orchestrator
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /oauth2/authorize:
    get:
      summary: OAuth2 Authorization Endpoint
      parameters:
        - in: query
          name: client_id
          schema: { type: string }
        - in: query
          name: redirect_uri
          schema: { type: string }
        - in: query
          name: response_type
          schema: { type: string, example: code }
        - in: query
          name: scope
          schema: { type: string }
        - in: query
          name: state
          schema: { type: string }
      responses:
        '302': { description: Redirect with code }
  /oauth2/token:
    post:
      summary: OAuth2 Token Endpoint
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type: { type: string }
                code: { type: string }
                redirect_uri: { type: string }
                client_id: { type: string }
                client_secret: { type: string }
                code_verifier: { type: string }
      responses:
        '200': { description: TokenResponse }
  /analyze:
    post:
      summary: Analyze feature vector (ml-orchestrator)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                features:
                  type: array
                  items: { type: number }
      responses:
        '200': { description: Score and anomaly flag }
