version: '3.8'

services:
  # PostgreSQL Primary
  postgres-primary:
    image: postgres:16-alpine
    container_name: shieldx-postgres-primary
    environment:
      POSTGRES_USER: shieldx
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-shieldx_secure_pass_2025}
      POSTGRES_DB: shieldx
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres-primary-data:/var/lib/postgresql/data
      - ./infra/db/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - shieldx-data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shieldx"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "effective_cache_size=1GB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"

  # Redis Primary
  redis-primary:
    image: redis:7-alpine
    container_name: shieldx-redis-primary
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --tcp-backlog 511
      --timeout 300
      --tcp-keepalive 60
    volumes:
      - redis-primary-data:/data
    ports:
      - "6379:6379"
    networks:
      - shieldx-data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Replica
  redis-replica:
    image: redis:7-alpine
    container_name: shieldx-redis-replica
    command: >
      redis-server
      --replicaof redis-primary 6379
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis-replica-data:/data
    ports:
      - "6380:6379"
    networks:
      - shieldx-data
    depends_on:
      - redis-primary
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # HAProxy Load Balancer
  haproxy:
    image: haproxy:2.9-alpine
    container_name: shieldx-haproxy
    volumes:
      - ./infra/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./infra/haproxy/certs:/etc/haproxy/certs:ro
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"  # Stats page
    networks:
      - shieldx-data
    depends_on:
      - postgres-primary
      - redis-primary
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8404/stats"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Backup Manager
  backup-manager:
    image: postgres:16-alpine
    container_name: shieldx-backup-manager
    environment:
      POSTGRES_HOST: postgres-primary
      POSTGRES_USER: shieldx
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-shieldx_secure_pass_2025}
      BACKUP_SCHEDULE: "0 2 * * *"
      BACKUP_RETENTION_DAYS: 30
    volumes:
      - ./backups:/backups
      - ./infra/db/backup-scripts:/scripts
    networks:
      - shieldx-data
    depends_on:
      - postgres-primary
    entrypoint: ["/scripts/backup-manager.sh"]

volumes:
  postgres-primary-data:
  redis-primary-data:
  redis-replica-data:

networks:
  shieldx-data:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
