# ShieldX Gateway Production Configuration

gateway:
  port: 8080
  max_concurrent_requests: 10000
  request_timeout: 30s
  rate_limit_rps: 1000
  health_check_interval: 30s

  # TLS Configuration
  tls:
    enabled: false
    cert_file: "/etc/ssl/certs/gateway.crt"
    key_file: "/etc/ssl/private/gateway.key"

  # Service Discovery
  services:
    zero_trust:
      urls: 
        - "http://localhost:8091"
      timeout: 5s
      retries: 2
      
    ai_analyzer:
      urls:
        - "http://localhost:8087"
      timeout: 10s
      retries: 2
      
    isolation_vault:
      urls:
        - "http://localhost:8085"
      timeout: 5s
      retries: 1
      
    deception_engine:
      urls:
        - "http://localhost:8084"
      timeout: 5s
      retries: 1
      
    dynamic_maze:
      urls:
        - "http://localhost:8084"
      timeout: 5s
      retries: 1

# Circuit Breaker Configuration
circuit_breaker:
  failure_threshold: 5
  recovery_timeout: 30s
  max_requests: 100

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "/var/log/shieldx/gateway.log"

# Metrics Configuration
metrics:
  enabled: true
  port: 9090
  path: "/metrics"

# Security Configuration
security:
  max_request_size: "10MB"
  rate_limit_window: "1m"
  cors_enabled: false
  
# Performance Tuning
performance:
  max_idle_conns: 100
  max_idle_conns_per_host: 10
  idle_conn_timeout: "90s"
  response_header_timeout: "30s"