name: ML Service Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/shieldx-ml/requirements-test.txt

      - name: Run ML test suite
        working-directory: services/shieldx-ml
        run: |
          python run_tests.py

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ml-test-report
          path: services/shieldx-ml/test_report.json
          if-no-files-found: warn
