name: Policy Bundle CI

on:
  pull_request:
    paths:
      - 'pkg/policy/**'
      - 'services/shieldx-policy/policies/**'
      - 'services/shieldx-policy/policy-tests/**'
      - 'Makefile'

jobs:
  policy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # enable OIDC for cosign keyless
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Install opa and conftest
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa && sudo mv opa /usr/local/bin/opa
          curl -L -o conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v0.55.0/conftest_0.55.0_Linux_x86_64.tar.gz
          tar -xzf conftest.tar.gz conftest && sudo mv conftest /usr/local/bin/conftest
      - name: Build policyctl
        run: |
          mkdir -p bin dist
          go build -o bin/policyctl ./tools/cli/cmd/policyctl
      - name: Bundle policy (produce digest)
        run: |
          set -e
          DIGEST_LINE=$(./bin/policyctl bundle -dir services/shieldx-policy/policies/demo -out dist/policy-bundle.zip | grep '^digest:')
          echo "$DIGEST_LINE" | awk '{print $2}' > dist/digest.txt
          echo "Digest=$(cat dist/digest.txt)"
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0
        with:
          cosign-release: 'v2.4.1'
      - name: Cosign sign-blob (keyless)
        env:
          COSIGN_EXPERIMENTAL: 'true'
        run: |
          cosign sign-blob --yes --output-signature dist/policy-bundle.cosign.sig dist/digest.txt
      - name: Cosign verify-blob (keyless)
        run: |
          cosign verify-blob --signature dist/policy-bundle.cosign.sig dist/digest.txt
      - name: OPA unit tests
        run: |
          opa test -v services/shieldx-policy/policy-tests
      - name: Conftest check (example)
        run: |
          conftest test services/shieldx-policy/policy-tests/fixtures/deployment.json -p services/shieldx-policy/policy-tests
